import { ArrowRight, ChevronRight, Mail, ShieldCheck } from 'lucide-react'
import { SiteSeo } from './SiteSeo'
import { defaultFaqs, guidePages } from './content'
import { aboutSeo, contactSeo, faqSeo, guidesSeo, shippingReturnsSeo, type FaqEntry } from './metadata'

type EditorialPageProps = { kind: 'about' | 'faq' | 'guides' | 'contact' | 'shipping-returns'; faqs?: FaqEntry[] }

const Breadcrumbs = ({ label }: { label: string }) => <nav className="seo-landing__breadcrumbs" aria-label="Breadcrumb"><a href="/">Home</a><ChevronRight size={14} aria-hidden="true" /><span aria-current="page">{label}</span></nav>

export function EditorialPage({ kind, faqs = defaultFaqs }: EditorialPageProps) {
  if (kind === 'about') return <section className="seo-landing seo-editorial shell"><SiteSeo page={aboutSeo()} /><Breadcrumbs label="About SkinFox" /><header className="seo-landing__hero"><span className="eyebrow">SkinFox / about</span><h1>Thoughtful care, with the details in the open.</h1><p>SkinFox is an everyday skin, hair and body-care store built around clear product information, considered routines and a calmer way to choose.</p></header><div className="seo-editorial__columns"><article><span className="section-number">Our approach</span><h2>Care-led, label-first and easy to explore.</h2><p>We bring together skincare, body care, hair care and scalp-care formats for real daily routines. Product pages explain what a product is, who it is designed for and where the final pack remains the source of truth.</p><p>Find My Care is cosmetic routine guidance, not medical advice. We do not diagnose conditions or promise a treatment outcome. If symptoms persist or concern you, please speak with a qualified healthcare professional.</p></article><aside className="seo-editorial__contact"><ShieldCheck size={22} /><h2>Business details</h2><dl><div><dt>Marketed by</dt><dd>VEDICSOLVE PRIVATE LIMITED</dd></div><div><dt>Registered address</dt><dd>121, Karnal Industrial Area, Sector 3, HSIDC, Karnal, Haryana 132001, India</dd></div><div><dt>GSTIN</dt><dd>06AALCV9847N1ZA</dd></div><div><dt>Customer support</dt><dd><a href="mailto:contact@skinfox.in">contact@skinfox.in</a><br /><a href="tel:+917082048820">+91 70820 48820</a></dd></div></dl></aside></div><section className="seo-landing__callout"><strong>Need help with a product or order?</strong><a href="mailto:contact@skinfox.in">Contact SkinFox <Mail size={16} /></a></section></section>
  if (kind === 'faq') return <section className="seo-landing seo-editorial shell"><SiteSeo page={faqSeo(faqs)} /><Breadcrumbs label="FAQs" /><header className="seo-landing__hero"><span className="eyebrow">SkinFox / help & support</span><h1>Clear answers about products, orders and care.</h1><p>Find practical answers about SkinFox product information, cosmetic guidance, checkout, delivery and customer accounts.</p></header><section className="seo-faq" aria-label="Frequently asked questions">{faqs.map((item, index) => <details key={item.question} open={index === 0}><summary><span>{String(index + 1).padStart(2, '0')}</span>{item.question}</summary><p>{item.answer}</p></details>)}</section><div className="seo-landing__callout"><strong>Could not find your answer?</strong><a href="mailto:contact@skinfox.in">Email contact@skinfox.in <ArrowRight size={16} /></a></div></section>
  if (kind === 'contact') return <section className="seo-landing seo-editorial shell"><SiteSeo page={contactSeo()} /><Breadcrumbs label="Contact" /><header className="seo-landing__hero"><span className="eyebrow">SkinFox / contact</span><h1>We’re here to help with your care and your order.</h1><p>Send us your order ID or product question and the SkinFox support team will help you with the next step.</p></header><div className="seo-editorial__columns"><article><span className="section-number">Customer support</span><h2>Talk to SkinFox.</h2><p>Email <a href="mailto:contact@skinfox.in">contact@skinfox.in</a> or call <a href="tel:+917082048820">+91 70820 48820</a>. Please include your order ID or the email used at checkout so we can find the correct record.</p><p>Support hours: Monday to Saturday, 10:00 am–6:00 pm IST. We’ll respond as soon as possible during working hours.</p></article><aside className="seo-editorial__contact"><ShieldCheck size={22} /><h2>Business details</h2><dl><div><dt>Marketed by</dt><dd>VEDICSOLVE PRIVATE LIMITED</dd></div><div><dt>Address</dt><dd>121, Karnal Industrial Area, Sector 3, HSIDC, Karnal, Haryana 132001, India</dd></div><div><dt>GSTIN</dt><dd>06AALCV9847N1ZA</dd></div></dl></aside></div></section>
  if (kind === 'shipping-returns') return <section className="seo-landing seo-editorial shell"><SiteSeo page={shippingReturnsSeo()} /><Breadcrumbs label="Shipping & returns" /><header className="seo-landing__hero"><span className="eyebrow">SkinFox / delivery</span><h1>Shipping and returns, clearly explained.</h1><p>Delivery availability and estimated dates are confirmed at checkout after you enter a serviceable pincode.</p></header><div className="seo-editorial__columns"><article><span className="section-number">Delivery</span><h2>What happens after you order?</h2><p>Enter your pincode at checkout to see serviceability, shipping charges and the estimated delivery date. Once your order is confirmed, the My Orders area shows the courier, tracking number and latest delivery estimate when available.</p><p>Orders are shipped from the configured pickup location. If a courier cannot service a pincode, choose another saved address or contact support before placing the order.</p><span className="section-number">Returns</span><h2>Need help with an order?</h2><p>Return eligibility, timelines and refund handling depend on the order and the current SkinFox policy. Email <a href="mailto:contact@skinfox.in">contact@skinfox.in</a> with your order ID before sending anything back.</p></article><aside className="seo-editorial__contact"><ShieldCheck size={22} /><h2>At checkout</h2><dl><div><dt>Shipping charge</dt><dd>Shown before payment and waived when the applicable order threshold is met.</dd></div><div><dt>Payment</dt><dd>Secure online payment is handled by Razorpay.</dd></div><div><dt>Tracking</dt><dd>Displayed in My Orders after a shipment is booked.</dd></div></dl></aside></div></section>
  return <section className="seo-landing seo-editorial seo-guides shell"><SiteSeo page={guidesSeo()} /><Breadcrumbs label="Guides" /><header className="seo-landing__hero"><span className="eyebrow">SkinFox / care guides</span><h1>Practical guides for simpler everyday care.</h1><p>Label-led skincare, hair-care and body-care reading for people comparing products in India. No miracle claims—just useful context for choosing a routine.</p></header><section className="seo-guides__grid" aria-label="SkinFox care guides">{guidePages.map((guide) => <article key={guide.slug} id={guide.slug}><span className="section-number">Care guide</span><h2>{guide.title}</h2><p>{guide.excerpt}</p>{guide.sections.map((section) => <div key={section.heading}><h3>{section.heading}</h3><p>{section.body}</p></div>)}<a className="text-link" href={`/guides/${guide.slug}`}>Read the full guide <ArrowRight size={16} /></a></article>)}</section></section>
}
